### ISSUE TITLE
License MINEX Algorithm for new hardware device

### ISSUE THREAD

**Issue by sburdka** [usnistgov/minex#3]
Hello NIST Team,
We are planning to launch our own fingerprint scanner. Its based on GC307 optical camera sensor with anti fake authentication capabilities. Camera sensor has been interfaced with ARM 32 bit MCU for internal processing for fingerprint image validating and authentication.  
But we are planning to go with NIST Certification. please guide us to that.
Thank You.

**Comment by gfiumara** [comment]
The MINEX III evaluation runs on server-based x64 (Intel Xeon) hardware. If you can create a build of your algorithm on this architecture, you'll be able to [submit to MINEX III](https://www.nist.gov/itl/iad/image-group/participation-minex-iii). We do not currently have any evaluations running natively on ARM or any 32-bit architecture.
