### ISSUE TITLE
Minex III Validation - Template generation only fails

### ISSUE THREAD

**Issue by MikeNice-IB** [usnistgov/minex#5]
Attempting to submit a template generator-only submission package.   I have set 

export MINEXIII_GENERATOR_ONLY=TRUE
and returned 0 for *template_matcher in get_pids , but it does not create the submission package ...

Wed Sep  7 10:57:23 EDT 2022
Checking for generator-only designation... (yes: generator only) [DONE]
Checking for required packages... [OKAY]
Checking validation version... (201907011032) [OKAY]
Checking OS Version... (CentOS 7.6.1810) [OKAY]
Looking for core library... (libminexiii_integratedbiometrics_0002.so) [OKAY]
Checking configuration files... (no configs) [OKAY]
Checking for previous validation attempts... [OKAY]
Building... [OKAY]
Gathering CBEFF info... [OKAY]
Generating templates... [OKAY]
Matching templates... [FAIL]

********************************************************************************
The template matching log is invalid. Please review
/home/allusers/minex/minexiii/validation/validation_output/match.log
a001_02.gray.tmpl	a001_02.gray.tmpl	-1	0.000000
********************************************************************************
Wed Sep  7 10:58:05 EDT 2022
[cbeff.log](https://github.com/usnistgov/minex/files/9507395/cbeff.log)

**Comment by gfiumara** [comment]
You are returning an invalid return code (`-1`) and setting a score of `0.0`. For generator-only submissions, you should be setting a score of -1 and a return code of 0.
